### PR TITLE
Add Toggle mouse emulation with arrow keys when routing cursor

### LINKED ISSUE #20: Should routing by cursor key emulation be configurable
Some applications like Emacs under cygwin or some Linux app through putty or mintty handle mouse.
With the latest stable version of braille extender (I.E. 2018-08-14), theses apps stop working properly when I use routing cursor.
If I disable the keyboard movement emulator in patch.py by the following:
if 0 and obj.hasFocus and braille.handler._cursorPos and (obj.role == controlTypes.ROLE_TERMINAL or (obj.role == controlTypes.ROLE_EDITABLETEXT and braille.handler.tether == braille.handler.TETHER_REVIEW)):
The mouse aware apps rework but I loose the keyboard emulator for routing cursor.
So I suggest a config flag to enable and disable this feature as appropriate.
Something like:
if config.conf["brailleExtender"]['EmulateRouting'] and obj.hasFocus and braille.handler._cursorPos and (obj.role == controlTypes.ROLE_TERMINAL or (obj.role == controlTypes.ROLE_EDITABLETEXT and braille.handler.tether == braille.handler.TETHER_REVIEW)):
Could work fine.

### PR DESCRIPTION
**Pull request by daniel-1964**
Fixes #20 Some console applications handle mouse.
If mouse emulation with arrow keys is enabled theses applications stop to work correctly.

### CODE REVIEW

**Comment by Andre9642** [comment]
First of all, congratulation for your first pull request! Especially since my code is not very Readable and elegant. :) Thanks!
Concerning the text label in general settings, I will suggest something like that "Try to emulate keyboard movements via routing cursors" rather than "Emulates mouse with arrow keys". What do you think?

**Comment by daniel-1964** [comment]
Hi, 
Finally something like routewithcursorkeys should be fine. A gui label like Use cursor keys to route cursor could also be good enough no?

**Comment by Andre9642** [comment]
> A gui label like Use cursor keys to route cursor could also be good enough no?

Yes, I think. But specify "in review mode", it is important.

**Comment by Andre9642** [comment]
Thanks again for this work! One final point: what name should I use for you in authors / acknowledgments list?

**Comment by daniel-1964** [comment]
Euh you can use my own name "Daniel COTTO" if you want.

**Pull request merged**
