### PR TITLE
Python 3 transition

### PR DESCRIPTION
**Pull request by Andre9642**
Some features are temporarily unavailable. Overview of current status and future availability (checked = feature already compatible, not checked = will be Restored soon):

- [x] Reload two favorite braille display with shortcuts
- [x] Automatic review cursor tethering in terminal role like in PuTTY, Powershell, bash, cmd
- [x] Auto scroll
- [x] Switch between several input/output braille tables
- [x] Mark the text with special attributes through dot 7, dot 8 or both
- [x] Translate text easily in Unicode braille and vice versa. E.g.: u <-> ⠥
- [x] Convert quickly cell description to Unicode braille and vice versa. E.g.: 123 <--> ⠇
- [x] Quick launches
- [x] Gesture maps
- [x] Save/show a braille view
- [x] Information on current char (decimal, hexadecimal, octal and binary values)
- [x] Display the speech output in braille of a text selection
- [x] Display the documentation
- [x] Automatic update check
- [x] Settings
- [x] Say the current line during text scrolling either in review mode, or in focus mode or both
- [x] (Don't) interrupt speech when scrolling on same line
- [x] (Don't) interrupt speech for unknown gestures
- [x] Announce the character while moving with routing buttons
- [x] Lock braille keyboard
- [x] Reverse forward scroll and back scroll buttons
- [x] BRF mode
- [x] Hide/show dots 7 and 8
- [x] Use two output braille tables simultaneously
- [x] Display tab signs as spaces
- [x] Custom role labels
- [ ] Ensure Python 2 compatibility

[Download latest release (NVDA 2019.3 only)](https://andreabc.net/projects/NVDA_addons/BrailleExtender/latest?py3=1)

### CODE REVIEW

**Comment by zstanecic** [comment]
@Andre9642 
Hw it's going with this... how can i test this PR? Do we have a topic brach for this?

**Comment by Andre9642** [comment]
@zstanecic please open this ticket on GitHub. In my first post (regularly updated) you'll find details and a link to download the Python 3 compatible release. Thanks.

**Comment by zstanecic** [comment]
In which post?

**Comment by Andre9642** [comment]
@zstanecic https://github.com/Andre9642/BrailleExtender/pull/32#issue-301690660

**Comment by zstanecic** [comment]
O. K.

**Pull request merged**
