### PR TITLE
polish and croatian update of the interface.

### PR DESCRIPTION
**Pull request by zstanecic**
translation update

### CODE REVIEW

**Comment by Andre9642** [comment]
Hello,
Don't worry, I'll merge this when all strings for the next stable version is ready. In the meantime, you can continue to push on this PR. I resume the development starting next week. I'd like to release the next stable version before March, (ideally for NVDA 2018.1).
Thanks you,
André

**Comment by zstanecic** [comment]
Hi, can you guide me, how i can push new commits to the existing PR?



Wysłane z aplikacji Poczta dla Windows 10

Od: André-Abush Clause
Wysłano: poniedziałek, 5 lutego 2018 20:27
Do: Andre9642/BrailleExtender
DW: zstanecic; Author
Temat: Re: [Andre9642/BrailleExtender] polish and croatian update of theinterface. (#12)

Hello,
Don't worry, I'll merge this when all strings for the next stable version is ready. In the meantime, you can continue to push on this PR. I resume the development starting next week. I'd like to release the next stable version before March, (ideally for NVDA 2018.1).
Thanks you,
André

**Comment by Andre9642** [comment]
You just have to add more commits by pushing to your branch selected for your PR (Master in this case). As long as your PR is not merged, your changes will show up in your pull request. when in doubt, don't hesitate to view your Pr on GitHub directly. All activities are logged.

**Comment by zstanecic** [comment]
Hi andre, in the settings dialog, i cannot create profile for my handytech display. is this still unimplemented?

**Comment by Andre9642** [comment]
Don't worry, it is not yet present. But it happens! Thanks.

**Comment by Andre9642** [comment]
The NVDA menu bug should be fixed with latest commit (cf. https://github.com/nvaccess/nvda/issues/8086).
Could you confirm for me that everything is good for you? Thanks

**Comment by zstanecic** [comment]
Hi,
It is OK.
The bug is fixed.
I will sk to close the issue

Wysłane z aplikacji Poczta dla Windows 10

Od: André-Abush Clause
Wysłano: piątek, 16 marca 2018 03:34
Do: Andre9642/BrailleExtender
DW: zstanecic; Author
Temat: Re: [Andre9642/BrailleExtender] polish and croatian update of theinterface. (#12)

The NVDA menu bug should be fixed with latest commit (cf. nvaccess/nvda#8086).
Could you confirm for me that everything is good for you? Thanks

**Comment by Andre9642** [comment]
I propose to merge all your work. Do you agree or prefer to wait until the stable version and continue on this PR?

**Comment by zstanecic** [comment]
Do not merge this yet, because before the stable version i need to update the croatian translation, as well as fix some stylistic and yntactic changes, 
I am also fixing the translations of the fly

Wysłane z aplikacji Poczta dla Windows 10

Od: André-Abush Clause
Wysłano: czwartek, 5 kwietnia 2018 22:48
Do: Andre9642/BrailleExtender
DW: zstanecic; Author
Temat: Re: [Andre9642/BrailleExtender] polish and croatian update of theinterface. (#12)

I propose to merge all your work. Do you agree or prefer to wait until the stable version and continue on this PR?

**Comment by Andre9642** [comment]
OK, no problem. Thanks.

**Comment by zstanecic** [comment]
Andre, please merge this, so that all localizations can be aligned,
Thanks!
P.s. i will continue on this PR

**Comment by Andre9642** [comment]
Thanks you for all your work! I'll release a dev verison with your work. Unfortunately, you'll must open a pull request.

**Pull request merged**
